#!/usr/bin/env python3
"""
Generate bridge/link.ld from FAF header files.

Parses LuaAPI.h, lua/lua.h, and global.h for  asm("0x...")  declarations
and emits a GNU ld linker script that maps each symbol name (which is the
hex address string) to its actual numeric address in the SupCom:FA process.

Usage (from the bridge/ directory):
    python gen_link_script.py > link.ld
    # or just:
    python gen_link_script.py   # writes link.ld directly
"""

import re
import sys
from pathlib import Path

HEADERS = [
    Path("src/LuaAPI.h"),
    Path("src/lua/lua.h"),
    Path("src/global.h"),
]

# Match  asm("0x...")  anywhere in the line
ASM_RE = re.compile(r'asm\("(0x[0-9A-Fa-f]+)"\)')


def collect_symbols(headers):
    seen = set()
    symbols = []
    for h in headers:
        if not h.exists():
            print(f"/* WARNING: {h} not found, skipping */", file=sys.stderr)
            continue
        for line in h.read_text(encoding="utf-8", errors="replace").splitlines():
            for m in ASM_RE.finditer(line):
                addr_str = m.group(1).lower()
                addr_int = int(addr_str, 16)
                if addr_str not in seen:
                    seen.add(addr_str)
                    symbols.append((addr_str, addr_int))
    return symbols


def write_link_script(symbols, out_path=Path("link.ld")):
    lines = [
        "/* Auto-generated by gen_link_script.py — do not edit by hand. */",
        "/* Maps asm(\"0x...\") symbol names to absolute SupCom:FA addresses. */",
        "/* Build with MinGW GCC: cmake -G \"MinGW Makefiles\" ... */",
        "/* NOTE: No SECTIONS directive — MinGW's built-in PE script handles  */",
        "/* section layout. PROVIDE-only scripts extend it without overriding. */",
        "",
    ]
    for addr_str, addr_int in sorted(symbols, key=lambda x: x[1]):
        lines.append(f'PROVIDE("{addr_str}" = {addr_str});')

    text = "\n".join(lines) + "\n"
    out_path.write_text(text, encoding="utf-8")
    print(f"Wrote {len(symbols)} symbol entries to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    syms = collect_symbols(HEADERS)
    write_link_script(syms)
