"""Tests for the free-text tool-call fallback parser (parse_fallback_tool_calls).

When a Q4 model bypasses native tool-calling and emits the call as plain
assistant ``content``, the bot must recover it instead of silently mapping the
whole blob to ``noop`` (the old behaviour, which dropped real actions). These
tests pin the recovery contract against an adversarial corpus generated by the
``enumerate-tool-call-mangling`` workflow and hand-vetted.

Contract:
- Line-anchored ``name(...)`` calls only (prose like "we could attack(), but..."
  must NOT fire).
- ``<think>...</think>`` leaks are stripped before scanning.
- A JSON object is a call only if it has a tool-name key (name/tool/function/
  action) resolving to a real tool — ``{"analysis": "..."}`` is a no-op.
- Truncated JSON (max_tokens cutoff) and Python-dict single quotes are repaired
  best-effort.
- Unknown tool names are dropped; calls are returned in source order, de-duped.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "server"))

from xml_tool_parser import parse_fallback_tool_calls  # noqa: E402

_CORPUS = json.loads(
    (Path(__file__).parent / "fixtures" / "tool_call_mangling_corpus.json").read_text(
        encoding="utf-8"
    )
)


def _norm(calls: list[dict]) -> list[tuple]:
    """Reduce a tool-call list to comparable (name, sorted-args) tuples."""
    return [
        (c["name"], json.dumps(c.get("args", {}), sort_keys=True, ensure_ascii=False))
        for c in calls
    ]


@pytest.mark.parametrize("case", _CORPUS, ids=[c["id"] for c in _CORPUS])
def test_corpus_case(case: dict) -> None:
    """Each adversarial case parses to exactly its vetted ground-truth calls."""
    got = parse_fallback_tool_calls(case["raw_text"])
    assert _norm(got) == _norm(case["expected"]), (
        f"\nshape={case['shape']}\nraw={case['raw_text']!r}"
        f"\nwhy={case.get('why', '')}"
        f"\nexpected={case['expected']}\ngot={got}"
    )


def test_empty_and_none_are_safe() -> None:
    assert parse_fallback_tool_calls("") == []
    assert parse_fallback_tool_calls(None) == []  # type: ignore[arg-type]


def test_unknown_tool_name_dropped() -> None:
    # A structurally valid call to a non-existent tool must not leak through.
    assert (
        parse_fallback_tool_calls('{"name": "nuke_everything", "arguments": {}}') == []
    )


def test_scenario1_regression_action_not_lost() -> None:
    """The real failure: an *action* free-texted in the scenario-1 shape.

    Old fallback turned this into noop and dropped the attack. It must now be
    recovered as a real attack call.
    """
    raw = 'attack\n{"unit_type": "land", "force_size": "medium"}'
    got = parse_fallback_tool_calls(raw)
    assert got == [
        {"name": "attack", "args": {"unit_type": "land", "force_size": "medium"}}
    ]


def test_prose_naming_tools_does_not_fire() -> None:
    raw = "I should attack soon, but let me scout first and maybe defend the base."
    assert parse_fallback_tool_calls(raw) == []
